version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: dev_project-decorators_postgres
    environment:
      POSTGRES_DB: project-decorators
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:6
    container_name: dev_project-decorators_redis
    volumes:
      - type: volume
        source: redis-data
        target: /var/lib/redis
    ports:
      - '6379:6379'
  
volumes:
  postgres-data:
    name: dev_project-decorators_postgres-data
  redis-data:
    name: dev_project-decorators_redis-data
